# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoffeeProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoffeeProject

pod "Alamofire"
pod "SDWebImage"
pod "lottie-ios"

  target 'CoffeeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoffeeProjectUITests' do
    # Pods for testing
  end

end
